name: Deploy to Server

on:
  push:
    branches:
      - master # Change this to your main branch nam
  pull_request:
    branches:
      - master # Change this to your main branch nam

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            "cd /var/www/git

             # Create .env for the server
            echo "REACT_APP_CONVERTKIT_KEY=${{ secrets.REACT_APP_CONVERTKIT_KEY }}" >> server/.env
            echo "REACT_APP_CONVERTKIT_ID=${{ secrets.REACT_APP_CONVERTKIT_ID }}" >> server/.env
            echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> server/.env

            # Create .env for the welsan
            echo "REACT_APP_CONVERTKIT_KEY=${{ secrets.REACT_APP_CONVERTKIT_KEY }}" >> welsan/.env
            echo "REACT_APP_CONVERTKIT_ID=${{ secrets.REACT_APP_CONVERTKIT_ID }}" >> welsan/.env
            echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> welsan/.env 

            ./.scripts/deploy.sh"
