name: Deploy to Server

on:
  push:
    branches:
      - master # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh user@your-server-ip << 'EOF'
            cd /var/www/git/* || exit
            git pull origin master  # Change to your main branch
            cd server
            npm install
            cd ../frontend
            npm install
            npm run build
            rm -rf /var/www/welsan/*
            mv build /var/www/welsan
          EOF
